name: CI Tests and Sync Early

on:
    push:
        branches:
            - main

jobs:
    test-and-sync:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: Run Tests
                # Ejecuta los tests que están en src/test/java
              run: mvn test

            - name: Update Early Branch
                # Solo se ejecuta si los tests se evaluaron satisfactoriamente
              if: success()
              run: |
                  git config --global user.name "github-actions[bot]"
                  git config --global user.email "github-actions[bot]@users.noreply.github.com"
                  git checkout early
                  git merge main --ff-only
                  git push origin early